bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 5000
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose: {plugin: "nav2_bt_navigator::NavigateToPoseNavigator"}
    navigate_through_poses: {plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"}
    error_code_names: ["compute_path_error_code", "follow_path_error_code"]

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 3.0
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 60.0

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: True

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.70 #ปรับความเร็วสูงสุดที่ต้องการตรงนี้
      lookahead_dist: 1.0
      min_lookahead_dist: 0.5
      max_lookahead_dist: 1.5
      use_collision_detection: false
      transform_tolerance: 5.0
      
      max_linear_accel: 0.05
      max_linear_decel: 0.05
      use_velocity_scaled_lookahead_dist: false
      
    
      use_approach_linear_velocity_scaling: true  
      approach_velocity_scaling_dist: 2.0         
      min_approach_linear_velocity: 0.05          
      

      max_linear_accel: 0.2
      max_linear_decel: 0.2
      use_velocity_scaled_lookahead_dist: false


velocity_smoother:
  ros__parameters:
    use_sim_time: false
    smoothing_frequency: 10.0
    scale_velocities: false
    feedback: "OPEN_LOOP"
    
    max_velocity: [0.70, 0.0, 0.5] #ความเร็วเดินหน้าสูงสุด,สะไลค์ข้าง,ความเร็วหมุนตัว
    min_velocity: [-0.3, 0.0, -0.5] 
    

    max_accel: [0.05, 0.0, 0.4]      
    max_decel: [-1.0, 0.0, -1.0] 

    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      update_frequency: 10.0
      publish_frequency: 5.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      robot_radius: 0.25
      transform_tolerance: 5.0
      plugins: ["obstacle_layer", "inflation_layer"]
      
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: lidar_source #scan_source
        
       
        lidar_source:
          data_type: PointCloud2
          topic: /velodyne_points
          sensor_frame: velodyne
          marking: true
          clearing: true
          model_type: 1 
          obstacle_range: 8.0   
          raytrace_range: 9.0   
          min_obstacle_height: 0.5 # [ปรับ] ลดลงมาหน่อยเผื่อของเตี้ยๆ
          max_obstacle_height: 2.0
          expected_update_rate: 0.3 # 20Hz tolerance

        # ส่วนของ RPLidar (2D - 10Hz) [เปิดใช้งานแล้ว]
        scan_source:
          topic: /scan_filtered
          data_type: LaserScan
          marking: true
          clearing: true
          min_obstacle_height: 0.0 # 2D Scan ถือว่าเป็นระนาบ
          max_obstacle_height: 2.0
          obstacle_range: 5.0      # RPLidar เชื่อถือได้ระยะนี้
          raytrace_range: 6.0
          inf_is_valid: true
          expected_update_rate: 0.2 # 10Hz tolerance

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.35

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      update_frequency: 10.0 
      publish_frequency: 5.0
      global_frame: map
      robot_base_frame: base_link
      rolling_window: false
      width: 15
      height: 15
      resolution: 0.1
      transform_tolerance: 5.0
      
      plugins: ["static_layer", "stvl_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        enabled: true

      stvl_layer:
        plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
        enabled: true
        publish_voxel_map: true
        voxel_decay: 2.0      
        voxel_size: 0.05
        transform_tolerance: 5.0
        
        
        observation_sources: lidar_source #scan_source
        
        
        lidar_source:
          data_type: PointCloud2
          topic: /velodyne_points
          sensor_frame: velodyne
          marking: true
          clearing: true
          model_type: 1 
          obstacle_range: 3.5   
          raytrace_range: 4.0   
          min_obstacle_height: 0.5 
          max_obstacle_height: 2.0 
          expected_update_rate: 0.7 

        
        scan_source:
          topic: /scan_filtered
          data_type: LaserScan
          marking: true
          clearing: true
          min_obstacle_height: 0.0 
          max_obstacle_height: 2.0
          obstacle_range: 5.0     
          raytrace_range: 6.0
          inf_is_valid: true
          expected_update_rate: 0.7 

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 1.5
        inflation_radius: 0.35
planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 1.0
    planner_plugins: ["GridBased"]
    GridBased: {plugin: "nav2_navfn_planner::NavfnPlanner", tolerance: 0.5}

behavior_server:
  ros__parameters:
    use_sim_time: false
    behavior_plugins: ["spin", "backup", "wait"]
    spin: {plugin: "nav2_behaviors::Spin"}
    backup: {plugin: "nav2_behaviors::BackUp"}
    wait: {plugin: "nav2_behaviors::Wait"}
    time_allowance: 10.0
    global_frame: map
    local_frame: odom
    robot_base_frame: base_link

smoother_server:
  ros__parameters:
    use_sim_time: false
    smoother_plugins: ["simple_smoother"]
    simple_smoother: {plugin: "nav2_smoother::SimpleSmoother"}

waypoint_follower:
  ros__parameters:
    use_sim_time: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint: {plugin: "nav2_waypoint_follower::WaitAtWaypoint"}

route_server:
  ros__parameters:
    use_sim_time: false
    operations: ["AdjustSpeedLimit"]
    AdjustSpeedLimit: {plugin: "nav2_route::AdjustSpeedLimit"}
    edge_cost_functions: ["DistanceScorer"]
    DistanceScorer: {plugin: "nav2_route::DistanceScorer"}

collision_monitor:
  ros__parameters:
    use_sim_time: false
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_smoothed" 
    cmd_vel_out_topic: "cmd_vel"          
    transform_tolerance: 0.2
    source_timeout: 5.0
    stop_pub_timeout: 2.0
    
    polygons: ["PolygonStop","PolygonSlow"]
    observation_sources: ["lidar_points", "scan_source"] # <--- ใช้ 2 ตาช่วยกัน

    PolygonStop:
      # type: "circle"
      # radius: 0.45
      type: "polygon"
      points: "[[0.3, 0.1], [0.3, -0.1], [0.0, -0.1], [0.0, 0.1]]"
      action_type: "stop"
      min_points: 4
      visualize: True
      polygon_pub_topic: "polygon_stop"
      enabled: false
    PolygonSlow:
      # type: "circle"
      # radius: 0.70
      type: "polygon"
      points: "[[0.5, 0.2], [0.5, -0.2], [0.0, -0.2], [0.0, 0.2]]"
      action_type: "slowdown"
      min_points: 4  # max_points: 3 for Humble
      slowdown_ratio: 0.8
      visualize: True
      polygon_pub_topic: "polygon_slowdown"
      enabled: false
    observation_sources: ["scan", "pointcloud"] 
    scan:
      type: "scan"
      topic: "/scan_filtered"
      enabled: false
    pointcloud:
      type: "pointcloud"
      topic: "/velodyne_points"
      enabled: True
      min_height: 0.05          
      max_height: 2.0   

docking_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 10.0
    base_frame: "base_link"
    fixed_frame: "odom"
    dock_plugins: ["simple_charging_dock"]
    simple_charging_dock: 
      plugin: "opennav_docking::SimpleChargingDock"
    docking_threshold: 0.05
    use_external_detection_pose: true

lifecycle_manager:
  ros__parameters:
    use_sim_time: false
    autostart: True
    node_names: ['map_server', 'controller_server', 'planner_server', 'behavior_server', 
                'bt_navigator', 'velocity_smoother', 'smoother_server',
                'route_server', 'waypoint_follower', 'collision_monitor', 'docking_server']