ekf_filter_node:
    ros__parameters:
            # frequency: 20.0
            #frequency: 50.0
            frequency: 25.0
            two_d_mode: true
            publish_tf: true
    
            map_frame: map             
            odom_frame: odom            
            base_link_frame: base_footprint
            world_frame: odom 

            #x     , y     , z,
            #roll  , pitch , yaw,
            #vx    , vy    , vz,
            #vroll , vpitch, vyaw,
            #ax    , ay    , az
            odom0: odom_raw
            odom0_config: [false, false, false,
                        false, false, false,
                        true, true, false,
                        false, false, true,
                        false, false, false]

            imu0: imu/data_raw
            imu0_config: [false, false, false,
                        false, false, true,
                        false, false, false,
                        false, false, true,
                        false, false, false]     

imu_filter:
    ros__parameters:
        stateless: false
        use_mag: false
        publish_tf: false
        reverse_tf: false
        fixed_frame: "odom"
        constant_dt: 0.0
        publish_debug_topics: false
        world_frame: "enu"
        gain: 0.1
        zeta: 0.0
        mag_bias_x: 0.0
        mag_bias_y: 0.0
        mag_bias_z: 0.0
        orientation_stddev: 0.0

usb_camera:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 15.0
      io_method: "mmap"
      frame_id: "camera"
        #pixel_format: "yuyv"  # see usb_cam/supported_formats for list of supported formats
        #av_device_format: "YUYV"
      image_width: 1280 #1280
      image_height: 460 #460 
      camera_name: "test_camera"
      camera_info_url: "package://usb_cam/config/camera_info.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: true
      white_balance: 2000
      autoexposure: true
      exposure: 100
      autofocus: false
      focus: -1

#60degree laser scan filter chain
scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: front_right_angle 
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: 1.8314 #2.25
        upper_angle: 2.46
        #lsmgop:
    
    filter2:
      name: front_left_angle 
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: -2.8536 #-2.41
        upper_angle: -1.8064 #-2.25
    
    filter3:
      name: back_right_angle 
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: 0.59 #0.1914 #0.59
        upper_angle: 0.84 #1.2386 #0.84   
    
    filter4:
      name: back_left_angle 
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: -0.8 #-1.2036 #-0.80
        upper_angle: -0.56 #-0.1564 #-0.56   

    filter5:
      name: speckle_filter
      type: laser_filters/LaserScanSpeckleFilter
      params:
        filter_type: 0
        max_range: 2.0
        max_range_difference: 0.1
        filter_window: 7
    
    # filter1:
    #   name: box_filter
    #   type: laser_filters/LaserScanRangeFilter
    #   params:
    #     use_message_range_limits: false   # if not specified defaults to false
    #     lower_threshold: 0.15              # if not specified defaults to 0.0
    #     upper_threshold: 1.0              # if not specified defaults to 100000.0
    #     lower_replacement_value: -.inf    # if not specified defaults to NaN
    #     upper_replacement_value: .inf     # if not specified defaults to NaN

