/**:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "rgbd_frame"
      pixel_format: "yuyv2rgb"
      image_width: 640
      image_height: 360
      camera_name: "test_camera"
      camera_info_url: "file:///home/smr/workspaces/mini_amr/amrROS2_ws/src/bringup/config/camera_info_360p.yaml"

