# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NavigationWB.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Navigation(object):
    def setupUi(self, Navigation):
        Navigation.setObjectName("Navigation")
        Navigation.resize(840, 630)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Navigation)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(Navigation)
        #self.frame_2.setMaximumSize(QtCore.QSize(230, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.qt_pose_table_view = QtWidgets.QTableView(self.frame_2)
        #self.qt_pose_table_view.setMaximumSize(QtCore.QSize(225, 16777215))
        self.qt_pose_table_view.setObjectName("qt_pose_table_view")
        self.verticalLayout_2.addWidget(self.qt_pose_table_view)
        self.qt_auto_add_goal_checkbox = QtWidgets.QCheckBox(self.frame_2)
        self.qt_auto_add_goal_checkbox.setObjectName("qt_auto_add_goal_checkbox")
        self.verticalLayout_2.addWidget(self.qt_auto_add_goal_checkbox)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(Navigation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.qt_delete_all_button = QtWidgets.QPushButton(self.frame)
        self.qt_delete_all_button.setMinimumSize(QtCore.QSize(0, 50))
        self.qt_delete_all_button.setObjectName("qt_delete_all_button")
        self.gridLayout_2.addWidget(self.qt_delete_all_button, 10, 2, 1, 1)
        self.qt_delete_button = QtWidgets.QPushButton(self.frame)
        self.qt_delete_button.setMinimumSize(QtCore.QSize(0, 50))
        self.qt_delete_button.setObjectName("qt_delete_button")
        self.gridLayout_2.addWidget(self.qt_delete_button, 10, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.qt_x_lcdnumber = QtWidgets.QLCDNumber(self.frame_4)
        self.qt_x_lcdnumber.setMinimumSize(QtCore.QSize(0, 30))
        self.qt_x_lcdnumber.setProperty("value", 0.0)
        self.qt_x_lcdnumber.setObjectName("qt_x_lcdnumber")
        self.horizontalLayout_4.addWidget(self.qt_x_lcdnumber)
        self.qt_y_lcdnumber = QtWidgets.QLCDNumber(self.frame_4)
        self.qt_y_lcdnumber.setMinimumSize(QtCore.QSize(0, 30))
        self.qt_y_lcdnumber.setObjectName("qt_y_lcdnumber")
        self.horizontalLayout_4.addWidget(self.qt_y_lcdnumber)
        self.qt_angle_lcdnumber = QtWidgets.QLCDNumber(self.frame_4)
        self.qt_angle_lcdnumber.setMinimumSize(QtCore.QSize(0, 30))
        self.qt_angle_lcdnumber.setObjectName("qt_angle_lcdnumber")
        self.horizontalLayout_4.addWidget(self.qt_angle_lcdnumber)
        self.gridLayout_2.addWidget(self.frame_4, 11, 1, 1, 2)
        self.qt_next_button = QtWidgets.QPushButton(self.frame)
        self.qt_next_button.setMinimumSize(QtCore.QSize(0, 70))
        self.qt_next_button.setMaximumSize(QtCore.QSize(107, 16777215))
        self.qt_next_button.setObjectName("qt_next_button")
        self.gridLayout_2.addWidget(self.qt_next_button, 1, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.qt_ang_lcdnumber = QtWidgets.QLCDNumber(self.groupBox_2)
        self.qt_ang_lcdnumber.setMinimumSize(QtCore.QSize(0, 30))
        self.qt_ang_lcdnumber.setProperty("intValue", 50)
        self.qt_ang_lcdnumber.setObjectName("qt_ang_lcdnumber")
        self.verticalLayout_4.addWidget(self.qt_ang_lcdnumber)
        self.qt_ang_slider = QtWidgets.QSlider(self.groupBox_2)
        self.qt_ang_slider.setMaximum(100)
        self.qt_ang_slider.setProperty("value", 50)
        self.qt_ang_slider.setOrientation(QtCore.Qt.Horizontal)
        self.qt_ang_slider.setObjectName("qt_ang_slider")
        self.verticalLayout_4.addWidget(self.qt_ang_slider)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.qt_vel_lcdnumber = QtWidgets.QLCDNumber(self.groupBox)
        self.qt_vel_lcdnumber.setMinimumSize(QtCore.QSize(0, 30))
        self.qt_vel_lcdnumber.setProperty("intValue", 50)
        self.qt_vel_lcdnumber.setObjectName("qt_vel_lcdnumber")
        self.verticalLayout_3.addWidget(self.qt_vel_lcdnumber)
        self.qt_vel_slider = QtWidgets.QSlider(self.groupBox)
        self.qt_vel_slider.setMaximum(100)
        self.qt_vel_slider.setProperty("value", 50)
        self.qt_vel_slider.setOrientation(QtCore.Qt.Horizontal)
        self.qt_vel_slider.setObjectName("qt_vel_slider")
        self.verticalLayout_3.addWidget(self.qt_vel_slider)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout_2.addLayout(self.verticalLayout, 12, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.qt_bat_prc_lcdnumber = QtWidgets.QLCDNumber(self.groupBox_5)
        self.qt_bat_prc_lcdnumber.setMinimumSize(QtCore.QSize(0, 30))
        self.qt_bat_prc_lcdnumber.setObjectName("qt_bat_prc_lcdnumber")
        self.qt_bat_prc_lcdnumber.setVisible(False)
        self.gridLayout_3.addWidget(self.qt_bat_prc_lcdnumber, 0, 1, 1, 1)
        self.qt_bat_vol_lcdnumber = QtWidgets.QLCDNumber(self.groupBox_5)
        self.qt_bat_vol_lcdnumber.setMinimumSize(QtCore.QSize(0, 30))
        self.qt_bat_vol_lcdnumber.setObjectName("qt_bat_vol_lcdnumber")
        self.gridLayout_3.addWidget(self.qt_bat_vol_lcdnumber, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_5, 14, 1, 1, 2)
        self.qt_add_current_pose_button = QtWidgets.QPushButton(self.frame)
        self.qt_add_current_pose_button.setMinimumSize(QtCore.QSize(0, 50))
        self.qt_add_current_pose_button.setObjectName("qt_add_current_pose_button")
        self.gridLayout_2.addWidget(self.qt_add_current_pose_button, 9, 2, 1, 1)
        self.qt_A_checkbox = QtWidgets.QCheckBox(self.frame)
        self.qt_A_checkbox.setChecked(True)
        self.qt_A_checkbox.setObjectName("qt_A_checkbox")
        self.qt_A_checkbox.setVisible(False)
        self.gridLayout_2.addWidget(self.qt_A_checkbox, 5, 1, 1, 1)
        self.qt_load_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qt_load_button.sizePolicy().hasHeightForWidth())
        self.qt_load_button.setSizePolicy(sizePolicy)
        self.qt_load_button.setMinimumSize(QtCore.QSize(0, 35))
        self.qt_load_button.setObjectName("qt_load_button")
        self.gridLayout_2.addWidget(self.qt_load_button, 16, 1, 1, 1)
        self.qt_B_checkbox = QtWidgets.QCheckBox(self.frame)
        self.qt_B_checkbox.setChecked(True)
        self.qt_B_checkbox.setObjectName("qt_B_checkbox")
        self.qt_B_checkbox.setVisible(False)
        self.gridLayout_2.addWidget(self.qt_B_checkbox, 5, 2, 1, 1)
        self.qt_cancel_button = QtWidgets.QPushButton(self.frame)
        self.qt_cancel_button.setMinimumSize(QtCore.QSize(0, 35))
        self.qt_cancel_button.setObjectName("qt_cancel_button")
        #self.qt_cancel_button.setVisible(False) 
        self.gridLayout_2.addWidget(self.qt_cancel_button, 15, 1, 1, 1)
        self.qt_save_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qt_save_button.sizePolicy().hasHeightForWidth())
        self.qt_save_button.setSizePolicy(sizePolicy)
        self.qt_save_button.setMinimumSize(QtCore.QSize(0, 35))
        self.qt_save_button.setObjectName("qt_save_button")
        self.gridLayout_2.addWidget(self.qt_save_button, 16, 2, 1, 1)
        self.qt_go_button = QtWidgets.QPushButton(self.frame)
        self.qt_go_button.setMinimumSize(QtCore.QSize(0, 70))
        self.qt_go_button.setMaximumSize(QtCore.QSize(107, 16777215))
        self.qt_go_button.setObjectName("qt_go_button")
        self.gridLayout_2.addWidget(self.qt_go_button, 1, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.qt_rotate_left_button = QtWidgets.QPushButton(self.frame_3)
        self.qt_rotate_left_button.setMinimumSize(QtCore.QSize(0, 35))
        self.qt_rotate_left_button.setMaximumSize(QtCore.QSize(35, 16777215))
        self.qt_rotate_left_button.setObjectName("qt_rotate_left_button")
        self.gridLayout.addWidget(self.qt_rotate_left_button, 2, 0, 1, 1)
        self.qt_backward_button = QtWidgets.QPushButton(self.frame_3)
        self.qt_backward_button.setMinimumSize(QtCore.QSize(0, 35))
        self.qt_backward_button.setMaximumSize(QtCore.QSize(35, 16777215))
        self.qt_backward_button.setObjectName("qt_backward_button")
        self.gridLayout.addWidget(self.qt_backward_button, 3, 1, 1, 1)
        self.qt_forward_button = QtWidgets.QPushButton(self.frame_3)
        self.qt_forward_button.setMinimumSize(QtCore.QSize(0, 35))
        self.qt_forward_button.setMaximumSize(QtCore.QSize(35, 16777215))
        self.qt_forward_button.setObjectName("qt_forward_button")
        self.gridLayout.addWidget(self.qt_forward_button, 1, 1, 1, 1)
        self.qt_rotate_right_button = QtWidgets.QPushButton(self.frame_3)
        self.qt_rotate_right_button.setMinimumSize(QtCore.QSize(0, 35))
        self.qt_rotate_right_button.setMaximumSize(QtCore.QSize(35, 16777215))
        self.qt_rotate_right_button.setObjectName("qt_rotate_right_button")
        self.gridLayout.addWidget(self.qt_rotate_right_button, 2, 2, 1, 1)
        self.qt_stop_button = QtWidgets.QPushButton(self.frame_3)
        self.qt_stop_button.setMinimumSize(QtCore.QSize(0, 35))
        self.qt_stop_button.setMaximumSize(QtCore.QSize(35, 16777215))
        self.qt_stop_button.setObjectName("qt_stop_button")
        self.gridLayout.addWidget(self.qt_stop_button, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_3, 12, 2, 1, 1)
        self.qt_move_up_button = QtWidgets.QPushButton(self.frame)
        self.qt_move_up_button.setMinimumSize(QtCore.QSize(0, 50))
        self.qt_move_up_button.setObjectName("qt_move_up_button")
        self.gridLayout_2.addWidget(self.qt_move_up_button, 4, 1, 1, 1)
        self.qt_clone_button = QtWidgets.QPushButton(self.frame)
        self.qt_clone_button.setMinimumSize(QtCore.QSize(0, 50))
        self.qt_clone_button.setObjectName("qt_clone_button")
        self.gridLayout_2.addWidget(self.qt_clone_button, 9, 1, 1, 1)
        self.qt_move_down_button = QtWidgets.QPushButton(self.frame)
        self.qt_move_down_button.setMinimumSize(QtCore.QSize(0, 50))
        self.qt_move_down_button.setObjectName("qt_move_down_button")
        self.gridLayout_2.addWidget(self.qt_move_down_button, 4, 2, 1, 1)
        self.qt_rename_button = QtWidgets.QPushButton(self.frame)
        self.qt_rename_button.setMinimumSize(QtCore.QSize(0, 35))
        self.qt_rename_button.setObjectName("qt_rename_button")
        self.gridLayout_2.addWidget(self.qt_rename_button, 15, 2, 1, 1)
        self.qt_run_button = QtWidgets.QPushButton(self.frame)
        self.qt_run_button.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.qt_run_button.setFont(font)
        self.qt_run_button.setCheckable(True)
        self.qt_run_button.setObjectName("qt_run_button")
        #self.qt_run_button.setVisible(False)
        self.gridLayout_2.addWidget(self.qt_run_button, 0, 1, 1, 2)
        self.qt_C_checkbox = QtWidgets.QCheckBox(self.frame)
        self.qt_C_checkbox.setChecked(True)
        self.qt_C_checkbox.setObjectName("qt_C_checkbox")
        self.qt_C_checkbox.setVisible(False)
        self.gridLayout_2.addWidget(self.qt_C_checkbox, 6, 1, 1, 1)
        self.qt_D_checkbox = QtWidgets.QCheckBox(self.frame)
        self.qt_D_checkbox.setChecked(True)
        self.qt_D_checkbox.setObjectName("qt_D_checkbox")
        self.qt_D_checkbox.setVisible(False)
        self.gridLayout_2.addWidget(self.qt_D_checkbox, 6, 2, 1, 1)
        self.qt_apply_button = QtWidgets.QPushButton(self.frame)
        self.qt_apply_button.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setBold(True)
        self.qt_apply_button.setFont(font)
        self.qt_apply_button.setObjectName("qt_apply_button")
        self.qt_apply_button.setVisible(False)
        self.gridLayout_2.addWidget(self.qt_apply_button, 7, 1, 1, 2)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Navigation)
        QtCore.QMetaObject.connectSlotsByName(Navigation)

    def retranslateUi(self, Navigation):
        _translate = QtCore.QCoreApplication.translate
        Navigation.setWindowTitle(_translate("Navigation", "Navigation"))
        self.qt_auto_add_goal_checkbox.setText(_translate("Navigation", "Auto Add Goal to Target Pose"))
        self.qt_delete_all_button.setText(_translate("Navigation", "Delete All"))
        self.qt_delete_button.setText(_translate("Navigation", "Delete"))
        self.qt_next_button.setText(_translate("Navigation", "Next"))
        self.groupBox_2.setTitle(_translate("Navigation", "% Ang Vel"))
        self.groupBox.setTitle(_translate("Navigation", "% Lin Vel"))
        self.groupBox_5.setTitle(_translate("Navigation", "Battery"))
        self.label_2.setText(_translate("Navigation", "%"))
        self.label_2.setVisible(False)
        self.label.setText(_translate("Navigation", "%"))
        self.qt_add_current_pose_button.setText(_translate("Navigation", "Add"))
        self.qt_A_checkbox.setText(_translate("Navigation", "A"))
        self.qt_load_button.setText(_translate("Navigation", "Load"))
        self.qt_B_checkbox.setText(_translate("Navigation", "B"))
        self.qt_cancel_button.setText(_translate("Navigation", "Cancel"))
        self.qt_save_button.setText(_translate("Navigation", "Save As"))
        self.qt_go_button.setText(_translate("Navigation", "Go"))
        self.qt_rotate_left_button.setText(_translate("Navigation", "R L"))
        self.qt_backward_button.setText(_translate("Navigation", "B"))
        self.qt_forward_button.setText(_translate("Navigation", "F"))
        self.qt_rotate_right_button.setText(_translate("Navigation", "R R"))
        self.qt_stop_button.setText(_translate("Navigation", "S"))
        self.qt_move_up_button.setText(_translate("Navigation", "Move Up"))
        self.qt_clone_button.setText(_translate("Navigation", "Clone"))
        self.qt_move_down_button.setText(_translate("Navigation", "Move Down"))
        self.qt_rename_button.setText(_translate("Navigation", "Re-Name"))
        self.qt_run_button.setText(_translate("Navigation", "Run"))
        #self.qt_run_button.setVisible(False)
        self.qt_C_checkbox.setText(_translate("Navigation", "C"))
        self.qt_D_checkbox.setText(_translate("Navigation", "D"))
        self.qt_apply_button.setText(_translate("Navigation", "Apply"))
