/marker_localization_node:
  ros__parameters:
    marker_dictionary_name: DICT_APRILTAG_36h11
    marker_size: 0.1055
    markers_config: '{"1": {"x": 1.263, "y": 0.2259, "z": 0.5562, "roll": 1.6911,
      "pitch": -0.0981, "yaw": -2.4875}}'
