/marker_localization_node:
  ros__parameters:
    marker_dictionary_name: DICT_APRILTAG_36h11
    marker_size: 0.15
    markers_config: '{"1": {"x": 0.3153, "y": -0.5227, "z": 0.4926, "roll": 2.9391,
      "pitch": -1.1687, "yaw": 1.6205}}'
