<?xml version="1.0"?>
<package format="3">
  <name>amr_nav2_slam_bringup</name>
  <version>0.1.0</version>
  <description>Bringup Nav2 with existing map + Slam Toolbox (online_async) to build a new .posegraph</description>

  <maintainer email="you@example.com">Your Name</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Launch & ROS -->
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <!-- Nav2 -->
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>nav2_msgs</exec_depend>

  <!-- SLAM Toolbox -->
  <exec_depend>slam_toolbox</exec_depend>

  <!-- Common -->
  <exec_depend>rclcpp</exec_depend>
  <exec_depend>rclpy</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
